AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - k2works::spring-boot-handson
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringBootHandsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: k2works.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-boot-handson-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootHandsonApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringBootHandsonApi
